- name: apply common to all
  hosts: all
  remote_user: root
  become: yes
  gather_facts: false


    roles:
    - common


- name: apply main.yml to ele
  hosts: ELE
  remote_user: root
  become: yes
  gather_facts: false
     
    
    roles:
    - ELE    