- name: apply common to all
  hosts: all
  remote_user: root
  become: yes
  gather_facts: false
  roles:
    - common

- name: apply main.yml to siem
  hosts: 10.5.1.106
  remote_user: root
  become: yes
  gather_facts: false
  roles:
    - client  
