- name: install python
  yum:
    name:
      - python36
      - python3-PyMySQL
      - php-ldap
    state: present
    update_cache: yes

- name: create database for moodle
  mysql_db:
    name: moodle
    state: present
    
- name: Removes anonymous user account for localhost
  mysql_user:
    name: ''
    host: localhost
    state: absent
    
- name: Create moodle user with all privileges
  mysql_user:
    name: moodleman
    password: Epstein2012
    priv: '*.*:ALL'
    state: present

- name: Download moodle
  get_url:
    url: https://downloads.sourceforge.net/project/moodle/Moodle/stable38/moodle-latest-38.tgz?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fmoodle%2Ffiles%2FMoodle%2Fstable38%2Fmoodle-latest-38.tgz%2Fdownload&ts=1575888738&use_mirror=autoselect
    dest: /tmp/

- name: Preparing the Moodle program files
  become: yes
  become_user: root
  shell: |
    sudo tar -zxvf /tmp/moodle-latest-38.tgz -C /var/www/html
    mv /var/www/html/moodle/* /var/www/html
    chown -R apache:apache /var/www/
    mkdir -p /moodle/moodledata
    chown -R apache:apache /moodle
    chmod -R 700 /moodle
    semanage fcontext -a -t httpd_sys_rw_content_t "/moodle/moodledata(/.*)?"
    restorecon -R /moodle/moodledata

- name: Add moodle config
  template:
    src: moodleconfig
    dest: /var/www/html/config.php
    mode: 777
    
- name: Restarting webserver
  shell: |
    systemctl restart httpd
    systemctl restart mysqld
 
- name: Adding dbtype
  lineinfile:
    path: /var/www/html/config-dist.php
    regexp: "dbtype"
    line: "$CFG->dbtype    = 'mariadb';"
    
- name: Adding dbname
  lineinfile:
    path: /var/www/html/config-dist.php
    regexp: "dbname"
    line: "$CFG->dbname    = 'moodle';"

- name: Adding dbuser
  lineinfile:
    path: /var/www/html/config-dist.php
    regexp: "dbuser"
    line: "$CFG->dbuser    = 'moodleman';"
 
- name: Adding dbpass
  lineinfile:
    path: /var/www/html/config-dist.php
    regexp: "dbpass"
    line: "$CFG->dbpass    = 'Epstein2012';"

- name: Adding wwwroot
  lineinfile:
    path: /var/www/html/config-dist.php
    regexp: "wwwroot"
    line: "$CFG->wwwroot    = 'http://10.2.12.146';"

- name: Adding dataroot
  lineinfile:
    path: /var/www/html/config-dist.php
    regexp: "dataroot"
    line: "$CFG->dataroot    = '/moodle/moodledata';"

- name: Copying config
  shell: |
    cp /var/www/html/config-dist.php /var/www/html/config.php
    systemctl restart httpd

- name: Importing backup script
  template:
    src: backupscript
    dest: /root/.backupscript
    mode: 700

- name: Importing private key
  template:
    src: pkey
    dest: /root/.ssh/pkey
    mode: 700

- name: chmod pkey
  shell: |
    chmod 700 /root/.ssh/pkey

- name: add line to crontab if not present
  lineinfile:
    path: /etc/crontab
    regexp: '^0\ \*\ \*\ \*\ \*\ root \/root\/\.backupscript'
    line: '0 * * * * root /root/.backupscript'
    owner: root
    group: root
    mode: 0644

  
