- name: install python
  yum:
    name:
      - python36
      - python3-PyMySQL
    state: present
    update_cache: yes

- name: create database for moodle
  mysql_db:
    name: moodle
    state: present
    
- name: Removes anonymous user account for localhost
  mysql_user:
    name: ''
    host: localhost
    state: absent
    
- name: Create moodle user with all privileges
  mysql_user:
    name: moodleman
    password: Epstein2012
    priv: '*.*:ALL'
    state: present

- name: Download moodle
  get_url:
    url: https://download.moodle.org/download.php/stable38/moodle-latest-38.tgz
    dest: /tmp

- name: Unarchive Moodle
  unarchive:
    src: /tmp
    dest: /var/www/html

- name: Preparing the Moodle program files
  become: yes
  become_user: root
  shell: |
    chown -R apache:apache /var/www/
