- name: install python
  yum:
    name:
      - python36
      - python
    state: present
    update_cache: yes

- name: create database for moodle
  mysql_db:
    name: moodle
    state: present
    
- name: Removes anonymous user account for localhost
  mysql_user:
    name: ''
    host: localhost
    state: absent
    
- name: Create moodle user with all privileges
  mysql_user:
    name: moodleman
    password: Epstein2012
    priv: '*.*:ALL'
    state: present

- name: Preparing the Moodle program files
  become: yes
  become_user: root
  shell: |
    wget https://download.moodle.org/download.php/direct/stable32/moodle-3.2.1.tgz
    sudo tar -zxvf moodle-3.2.1.tgz -C /var/www/html
    sudo chown -R root:root /var/www/html/moodle