- name: install python
  yum:
    name:
      - python36
      - python3-PyMySQL
    state: present
    update_cache: yes

- name: create database for moodle
  mysql_db:
    name: moodle
    state: present
    
- name: Removes anonymous user account for localhost
  mysql_user:
    name: ''
    host: localhost
    state: absent
    
- name: Create moodle user with all privileges
  mysql_user:
    name: moodleman
    password: Epstein2012
    priv: '*.*:ALL'
    state: present

- name: Download moodle
  get_url:
    url: https://downloads.sourceforge.net/project/moodle/Moodle/stable38/moodle-latest-38.tgz?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fmoodle%2Ffiles%2FMoodle%2Fstable38%2Fmoodle-latest-38.tgz%2Fdownload&ts=1575888738&use_mirror=autoselect
    dest: /tmp/

- name: Preparing the Moodle program files
  become: yes
  become_user: root
  shell: |
    sudo tar -zxvf /tmp/moodle-latest-38.tgz -C /var/www/html
    mv /var/www/html/moodle/* /var/www/html
    chown -R apache:apache /var/www/
    mkdir -p /moodle/moodledata
    chown -R apache:apache /moodle
    chmod -R 777 /moodle
    semanage fcontext -a -t httpd_sys_rw_content_t "/moodle/moodledata(/.*)?"
    restorecon -R /moodle/moodledata

- name: Add moodle config
  template:
    src: moodleconfig
    dest: /var/www/html/config.php
    mode: 777