- name: Install elasticsearch
  yum:
    name:
      - java-1.8.0-openjdk-devel
      - elasticsearch
      - python
    state: present
    update_cache: yes

- name: start elasticsearch
  become: yes
  become_user: root
  service:
    name: elasticsearch
    state: started
    enabled: yes
    
- name: Downloading Splunk Enterprise
  shell: |
    wget -O splunk-8.0.0-1357bef0a7f6-linux-2.6-x86_64.rpm "https://www.splunk.com/bin/splunk/DownloadActivityServlet?architecture=x86_64&platform=linux&version=8.0.0&product=splunk&filename=splunk-8.0.0-1357bef0a7f6-linux-2.6-x86_64.rpm&wget=true"
    
- name: Installing Splunk Enterprise
  shell: |
    rpm -i splunk-8.0.0-1357bef0a7f6-linux-2.6-x86_64.rpm
    /opt/splunk/bin/./splunk start --accept-license --answer-yes
    /opt/splunk/bin/./splunk enable boot-start
    expect "Please enter a new password:"
    send "Epstein2012"
    expect "Please confirm new password:"
    send "Epstein2012"
    
- name: Opening Splunk ports
  shell: |
    firewall-cmd --permanent --add-port=8000/tcp
    firewall-cmd --reload