- name: importing elasticsearch gpg key
  become: yes
  become_user: root
  shell: |
    rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: create elasticsearch.repo
  become: yes
  become_user: root
  copy: 
    dest: "/etc/yum.repos.d/elasticsearch.repo"
    content: |
      [elasticsearch-6.x]
      name=Elasticsearch repository for 6.x packages
      baseurl=https://artifacts.elastic.co/packages/6.x/yum
      gpgcheck=1
      gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
      enabled=1
      autorefresh=1
      type=rpm-md    

- name: Install elasticsearch
  yum:
    name:
      - java-1.8.0-openjdk-devel
      - elasticsearch
      - python36
    state: present
    update_cache: yes

- name: start elasticsearch
  become: yes
  become_user: root
  service:
    name: elasticsearch
    state: started
    enabled: yes

- name: Change elasticsearch config
  shell: |
    sed -i s/\#network\.host\:............/network\.host\:\ localhost/g /etc/elasticsearch/elasticsearch.yml

- name: Rebooting
  reboot:

- name: Download Splunk Enterprise
  get_url:
    url: https://www.splunk.com/bin/splunk/DownloadActivityServlet?architecture=x86_64&platform=linux&version=8.0.0&product=splunk&filename=splunk-8.0.0-1357bef0a7f6-linux-2.6-x86_64.rpm&wget=true
    dest: /tmp/splunkenterprise

- name: Installing Splunk Enterprise
  expect:
    command: /opt/splunk/bin/./splunk start --accept-license --answer-yes
    responses:
      "Please enter an administrator username:": "root"
      "Please enter a new password:": "Epstein2012"
      "Please confirm new password:": "Epstein2012"

- name: Starting Splunk Enterprise
  shell: |
    /opt/splunk/bin/./splunk enable boot-start
    
- name: Opening Splunk ports
  shell: |
    firewall-cmd --permanent --add-port 8000/tcp
    firewall-cmd --reload
