- name: Install MariaDB
  yum:
<<<<<<< HEAD
     - mariadb-server
     - mariadb
     - python36
     - python3-PyMySQL
  state: present
=======
    name:
      - mariadb-server
      - mariadb
    state: present
>>>>>>> 70a7016acb0fc4064356b7af59a324e658c01d73
  
- name: start mariadb
  become: yes
  become_user: root
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Removes anonymous user account for localhost
  mysql_user:
    name: ''
    host: localhost
    state: absent
    
- name: Create backup directory
  shell: |
    mkdir /backups
    chmod 777 /backups
