- name: kinit admin to execute ipa commands
  expect:
    command: kinit admin
    responses:
      "Password for admin@GROEP5UVD.NL:": "Epstein2012"

- name: add ipa services
  shell: |
    ipa service-add smtp/g05-mailstor02.groep5uvd.nl
    ipa service-add imap/g05-mailstor02.groep5uvd.nl 
    ipa-getkeytab -s g05-ipa.groep5uvd.nl -p imap/g05-mailstor02.groep5uvd.nl -k /etc/dovecot/krb5.keytab

