- name: install required packages
  yum:
    name:
      - mariadb-server
      - postfix
      - dovecot
      - dovecot-mysql
    update_cache: yes
    
- name: start mariadb
  become: yes
  become_user: root
  service:
    name: mariadb
    state: started
    enabled: yes
    
- name: create database for mailserver
  mysql_db:
    name: mailserver
    state: present
    
- name: Removes anonymous user account for localhost
  mysql_user:
    name: ''
    host: localhost
    state: absent
    
- name: Create mailman user with all privileges
  mysql_user:
    name: mailman
    password: Epstein2012
    priv: '*.*:ALL'
    state: present
    
- name: copy createtables template
  template:
    src: createtables
    dest: /tmp/createtables
    mode: "600"
    
- name: Import table structure from template
  mysql_db:
    name: mailserver
    state: import
    target: /tmp/createtables
    
- name: copy postfix config
  template:
    src: postfixconfig
    dest: /etc/postfix/main.cf
    mode: "600"
    
- name: copy mailboxdomains
  template:
    src: mailboxdomains
    dest: /etc/postfix/mysql-virtual-mailbox-domains.cf
    mode: "600"
    
- name: copy mailboxmaps
  template:
    src: mailboxmaps
    dest: /etc/postfix/mysql-virtual-mailbox-maps.cf
    mode: "600"
    
- name: copy aliasmaps
  template:
    src: aliasmaps
    dest: /etc/postfix/mysql-virtual-alias-maps.cf
    mode: "600"
    
- name: copy email2email
  template:
    src: email2email
    dest: /etc/postfix/mysql-virtual-email2email.cf
    mode: "600"
    
- name: restart postfix
  become: yes
  become_user: root
  shell: |
    systemctl restart postfix
    