- name: install lamp stack
  yum:
    name:
      - httpd
      - mariadb-server
      - mariadb
      - php
      - php-mysqlnd
      - php-pdo
      - php-gd
      - php-mbstring
    state: present
    update_cache: yes

- name: start apache
  become: yes
  become_user: root
  service:
    name: httpd
    state: started
    enabled: yes

- name: start mariadb
  become: yes
  become_user: root
  service:
    name: mariadb
    state: started
    enabled: yes
    
- name: create database for moodle
  mysql_db:
    name: moodle
    state: present
    
- name: Removes anonymous user account for localhost
  mysql_user:
    name: ''
    host: localhost
    state: absent
    
- name: Create moodle user with all privileges
  mysql_user:
    name: moodleman
    password: Epstein2012
    priv: '*.*:ALL'
    state: present

- name: Preparing the Moodle program files
  become:yes
  become_user: root
  shell: |
    wget https://download.moodle.org/download.php/direct/stable32/moodle-3.2.1.tgz
    sudo tar -zxvf moodle-3.2.1.tgz -C /var/www/html
    sudo chown -R root:root /var/www/html/moodle
  
- name: adding firewall ports
  become: yes
  become_user: root
  shell: |
    firewall-cmd ––permanent ––add-port 80/tcp
    firewall-cmd --reload

- name: create index.html
  become: yes
  become_user: root
  copy: 
    dest: "/var/www/html/index.html"
    content: |
      <html>
       <head>
        <title>testpagina</title>
       </head>
       <body>
       <?php echo '<p>ayy lmao</p>'; ?> 
       </body>
      </html> 