- name: install lamp stack
  yum:
    name:
      - httpd
      - mariadb-server
      - mariadb
      - php
      - php-mysqlnd
      - php-pdo
      - php-gd
      - php-mbstring
    state: present
    update_cache: yes

- name: start apache
  become: yes
  become_user: root
  service:
    name: httpd
    state: started
    enabled: yes

- name: start mariadb
  become: yes
  become_user: root
  service:
    name: mariadb
    state: started
    enabled: yes
    
- name: [WARNING] DISABLING FIREWALL
  become: yes
  become_user: root
  shell: |
    sudo firewall-cmd ––permanent ––add-port=80/tcp
    sudo firewall-cmd --reload

- name: create index.html
  become: yes
  become_user: root
  copy: 
    dest: "/var/www/html/index.html"
    content: |
      <html>
       <head>
        <title>testpagina</title>
       </head>
       <body>
       <?php echo '<p>ayy lmao</p>'; ?> 
       </body>
      </html> 