- name: install lamp stack
  yum:
    name:
      - httpd
      - mariadb-server
      - mariadb
      - php
      - php-mysqlnd
      - php-pdo
      - php-gd
      - php-mbstring
      - php-pecl-zip
      - php-json
      - php-xml
      - python36
    state: present
    update_cache: yes

- name: Installing PhpMyAdmin
  shell: |
    wget https://files.phpmyadmin.net/phpMyAdmin/4.9.2/phpMyAdmin-4.9.2-english.tar.gz
    tar -zxvf phpMyAdmin-4.9.2-english.tar.gz
    mv -vn phpMyAdmin-4.9.2-english /usr/share/phpMyAdmin
    
- name: Configuring PhpMyAdmin
  shell: |
    cp -pr /usr/share/phpMyAdmin/config.sample.inc.php /usr/share/phpMyAdmin/config.inc.php
    sed -i -E "s/(?:\$cfg\[\'blowfish_secret\'\]\ \=\ \'\'\;)/$cfg['blowfish_secret'] = 'tu.88b/RHS-5K0Ut5fysBLUX:G;OFXtG';/g" /usr/share/phpMyAdmin/config.inc.php
    

- name: start apache
  become: yes
  become_user: root
  service:
    name: httpd
    state: started
    enabled: yes

- name: start mariadb
  become: yes
  become_user: root
  service:
    name: mariadb
    state: started
    enabled: yes
  
- name: adding firewall ports
  become: yes
  become_user: root
  shell: |
    firewall-cmd ––permanent ––add-port 80/tcp
    firewall-cmd --reload
