- name: install lamp stack
  yum:
    name:
      - httpd
      - mariadb-server
      - mariadb
      - php
      - php-mysqlnd
      - php-pdo
      - php-gd
      - php-mbstring
      - php-pecl-zip
      - php-json
      - php-xml
      - python36
    state: present
    update_cache: yes

- name: start apache
  become: yes
  become_user: root
  service:
    name: httpd
    state: started
    enabled: yes

- name: start mariadb
  become: yes
  become_user: root
  service:
    name: mariadb
    state: started
    enabled: yes
  
- name: adding firewall ports
  become: yes
  become_user: root
  shell: |
    firewall-cmd ––permanent ––add-port 80/tcp
    firewall-cmd --reload
