- name: Create .ssh dir for root
  file:
    path: /home/root/.ssh
    state: directory

- name: Setup authorized_keys for root
  template:
    src: authorized_keys
    dest: /home/root/.ssh/authorized_keys
    mode: "600"

- name: Give permissions to root for .ssh dir
  file:
    path: /home/root/
    owner: root
    group: root
    recurse: yes
      

- name: Disable SELinux
   shell: |
     setsebool -P antivirus_can_scan_system 1
     setsebool -P clamd_use_jit 1
    
- name: Install Epel Repository
  yum:
    name: epel-release
    state: present

- name: Install ClamAV
  yum:
    name:
      - clamav-server 
      - clamav-data 
      - clamav-update 
      - clamav-filesystem 
      - clamav 
      - clamav-scanner-systemd 
      - clamav-devel 
      - clamav-lib 
      - clamav-server-systemd
    state: present

- name: ClamAV configuratie
  shell: |
    sed -i -e "s/^Example/#Example/" /etc/clamd.d/scan.conf
    sed -i -e "s/#LocalSocket /LocalSocket /" /etc/clamd.d/scan.conf
    sed -i -e "s/^Example/#Example/" /etc/freshclam.conf

- name: Download virus definitions
  shell: |
    freshclam

- name: Make scan service
  shell: |
    nano /usr/lib/systemd/system/freshclam.service

- name: create scan file
  copy: 
    dest: "/usr/lib/systemd/system/freshclam.service"
    content: |
        [Unit]
        Description = freshclam scanner
        After = network.target

        [Service]
        Type = forking
        ExecStart = /usr/bin/freshclam -d -c 1
        Restart = on-failure
        PrivateTmp =true

        [Install]
        WantedBy=multi-user.target