- name: Create .ssh dir for root
  file:
    path: /root/.ssh
    state: directory

- name: Setup authorized_keys for root
  template:
    src: authorized_keys
    dest: /root/.ssh/authorized_keys
    mode: "600"

- name: Give permissions to root for .ssh dir
  file:
    path: /root
    owner: root
    group: root
    recurse: yes

- name: turn off password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: PasswordAuthentication no
    state: present

- name: restart sshd
  service:
    name: sshd
    state: restarted
      
- name: Updating repositories
  shell: |
    yum -y update

- name: Allow ClamAV to scan all files
  shell: |
    setsebool -P antivirus_can_scan_system 1
    setsebool -P clamd_use_jit 1
    
- name: Install Epel Repository
  yum:
    name: epel-release
    state: present

- name: Install ClamAV
  yum:
    name:
      - clamav-server 
      - clamav-data 
      - clamav-update 
      - clamav-filesystem 
      - clamav 
      - clamav-scanner-systemd 
      - clamav-devel 
      - clamav-lib 
      - clamav-server-systemd
      - python36
    state: present

- name: Install pexpect
  shell: |
    python3.6 -m pip install pexpect

- name: ClamAV configuratie
  shell: |
    sed -i -e "s/^Example/#Example/" /etc/clamd.d/scan.conf
    sed -i -e "s/#LocalSocket /LocalSocket /" /etc/clamd.d/scan.conf
    sed -i -e "s/^Example/#Example/" /etc/freshclam.conf

- name: Download virus definitions
  shell: |
    freshclam

- name: Create scan service file
  shell: |
    touch /usr/lib/systemd/system/freshclam.service

- name: Create scan file content
  copy: 
    dest: "/usr/lib/systemd/system/freshclam.service"
    content: |
        [Unit]
        Description = freshclam scanner
        After = network.target

        [Service]
        Type = forking
        ExecStart = /usr/bin/freshclam -d -c 1
        Restart = on-failure
        PrivateTmp =true

        [Install]
        WantedBy=multi-user.target

- name: Start antivirus services
  shell: |
    systemctl enable clamd@scan
    systemctl enable freshclam
    systemctl start clamd@scan
    systemctl start freshclam

- name: Install Chrony
  yum: 
    name:
    - chrony
    state: present
    
- name:
  shell: |
  systemctl enable chronyd
    
