- name: Installing bind-utils
  yum:
    name: 
    - bind-utils
    - freeipa-client
    state: present

- name: Setting the hostname
  shell: |
    echo "g05-client02.groep5uvd.nl" > /etc/hostname
    hostname g05-client02.groep5uvd.nl
  become: yes
  become_user: root

- name: Rebooting
  reboot:

- name: Opening Splunk ports
  shell: |
    firewall-cmd --permanent --add-port 80/tcp
    firewall-cmd --permanent --add-port 88/tcp
    firewall-cmd --permanent --add-port 88/udp
    firewall-cmd --permanent --add-port 389/tcp
    firewall-cmd --permanent --add-port 464/tcp
    firewall-cmd --permanent --add-port 464/udp
    firewall-cmd --permanent --add-port 123/tcp
    firewall-cmd --reload
 
- name: FreeIpa installation
  shell: |
    ipa-client-install --unattended --hostname g05-client02.groep5uvd.nl --server g05-ipa.groep5uvd.nl --domain groep5uvd.nl --password Epstein2012 --realm GROEP5UVD.NL -p admin --mkhomedir --force-join
