- name: Setting the hostname
  shell: |
    hostname ipa-client.groep5uvd.nl
    
- name: Installing bind-utils
  yum:
    - bind-utils
    - freeipa-client

- name: FreeIpa installation
  expect:
    command: ipa-client-install --mkhomedir
    responses:
      "Provide the domain name of your IPA server (ex: example.com):": "groep5uvd.nl"
      "Provide your IPA server name (ex: ipa.example.com):": "g05-ipa.groep5uvd.nl"
    timeout: null
