- name: Installing bind-utils
  yum:
    name: 
    - bind-utils
    - freeipa-client

- name: Setting the hostname
  shell: |
    hostname ipa-client.groep5uvd.nl
    
- name: FreeIpa installation
  expect:
    command: ipa-client-install --mkhomedir
    responses:
      "Provide the domain name of your IPA server (ex: example.com):": "groep5uvd.nl"
      "Provide your IPA server name (ex: ipa.example.com):": "g05-ipa.groep5uvd.nl"
      "Proceed with fixed values and no DNS discovery? [no]:": "yes"
      "Continue to configure the system with these values? [no]:": "yes"
      "User authorized to enroll computers:": "admin"
    timeout: 180
