- name: Installing required packages
  yum:
    name: 
    - bind-utils
    - freeipa-client
    - nfs-utils
    - thunderbird
    state: present

- name: Installing LibreOffice
  shell: |
    wget -P /tmp http://download.documentfoundation.org/libreoffice/stable/6.1.3/rpm/x86_64/LibreOffice_6.1.3_Linux_x86-64_rpm.tar.gz
    tar -xvf LibreOffice_6.1.3* -C /tmp/LibreOffice
    yum localinstall RPMS/*.rpm
    
- name: Setting the hostname
  shell: |
    echo "{{hostname|quote}}" > /etc/hostname
    hostname {{hostname|quote}}
  become: yes
  become_user: root

- name: Rebooting
  reboot:

- name: Opening Splunk ports
  shell: |
    firewall-cmd --permanent --add-port 80/tcp
    firewall-cmd --permanent --add-port 88/tcp
    firewall-cmd --permanent --add-port 88/udp
    firewall-cmd --permanent --add-port 389/tcp
    firewall-cmd --permanent --add-port 464/tcp
    firewall-cmd --permanent --add-port 464/udp
    firewall-cmd --permanent --add-port 123/tcp
    firewall-cmd --reload

- name: Adding IPA server to host file
  lineinfile:
    path: /etc/hosts
    regexp: '^10\.5\.1\.12'
    line: '10.5.1.12 g05-ipa.groep5uvd.net'
    owner: root
    group: root
    mode: 0644

- name: Make sure IPA client is not installed
  shell: |
    ipa-client-install --uninstall --unattended
  ignore_errors: yes
 
- name: FreeIpa installation
  shell: |
    ipa-client-install --unattended --hostname {{hostname|quote}} --server g05-ipa.groep5uvd.net --domain groep5uvd.net --password Epstein2012 --realm GROEP5UVD.NET -p admin --mkhomedir --force-join

- name: Create share directory
  shell: |
    mkdir -p /share

- name: mount NFS share
  shell: |
    mount -t nfs -o vers=4 10.5.1.14:/ /share

- name: add line to fstab if not present
  lineinfile:
    path: /etc/fstab
    regexp: '^10\.5\.1\.14'
    line: '10.5.1.14:/ /share nfs defaults,timeo=900,retrans=5,_netdev  0 0'
    owner: root
    group: root
    mode: 0644
