- name: Installing required packages
  yum:
    name: 
    - bind-utils
    - freeipa-client
    - nfs-utils
    - thunderbird
    - realmd
    - sssd
    - oddjob
    - oddjob-mkhomedir
    - adcli
    - samba-common
    - samba-common-tools
    - krb5-workstation
    state: present

- name: Installing LibreOffice
  shell: |
    wget https://download.documentfoundation.org/libreoffice/stable/6.3.4/rpm/x86_64/LibreOffice_6.3.4_Linux_x86-64_rpm.tar.gz -P /tmp
    tar -xvf /tmp/LibreOffice_6.3.4_Linux_x86-64_rpm.tar.gz -C /tmp
    yum localinstall /tmp/LibreOffice_6.3.4.2_Linux_x86-64_rpm/RPMS/*
    
- name: Setting the hostname
  shell: |
    echo "{{hostname|quote}}" > /etc/hostname
    hostname {{hostname|quote}}
  become: yes
  become_user: root

- name: Rebooting
  reboot:

- name: Joining domain
  expect:
    command: realm join ijsselstreek-university.nl -U Administrator
    responses:
     "Password for Administrator:": "Welkom01"

- name: Opening Splunk ports
  shell: |
    firewall-cmd --permanent --add-port 80/tcp
    firewall-cmd --permanent --add-port 88/tcp
    firewall-cmd --permanent --add-port 88/udp
    firewall-cmd --permanent --add-port 389/tcp
    firewall-cmd --permanent --add-port 464/tcp
    firewall-cmd --permanent --add-port 464/udp
    firewall-cmd --permanent --add-port 123/tcp
    firewall-cmd --reload

- name: Create share directory
  shell: |
    mkdir -p /share

- name: mount NFS share
  shell: |
    mount -t nfs -o vers=4 10.5.1.14:/ /share

- name: add line to fstab if not present
  lineinfile:
    path: /etc/fstab
    regexp: '^10\.5\.1\.14'
    line: '10.5.1.14:/ /share nfs defaults,timeo=900,retrans=5,_netdev  0 0'
    owner: root
    group: root
    mode: 0644
